FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

EXPOSE 3000
ENV HOSTNAME=0.0.0.0 \
    WATCHPACK_POLLING=true \
    WATCHPACK_POLLING_INTERVAL=1000 \
    CHOKIDAR_USEPOLLING=true \
    CHOKIDAR_INTERVAL=1000

CMD ["npm", "run", "dev:docker"]
